#!/bin/bash

# Configuration
DNS1="8.8.8.8"
DNS2="8.8.4.4"
SCRIPT_PATH="/usr/local/bin/dns-persist.sh"
RESOLV_CONF="/etc/resolv.conf"

# Check for root
if [[ $EUID -ne 0 ]]; then
   echo "Error: Please run with sudo."
   exit 1
fi

echo "--- DNS Persistence Installer ---"

# 1. Create the persistent worker script
cat <<EOF > $SCRIPT_PATH
#!/bin/bash
# Automatically generated by nsetup.sh
echo "nameserver $DNS1" > $RESOLV_CONF
echo "nameserver $DNS2" >> $RESOLV_CONF
EOF

chmod +x $SCRIPT_PATH

# 2. Run it immediately
$SCRIPT_PATH
echo "Done: DNS set to Google ($DNS1, $DNS2)."

# 3. Add to Cron for persistence (Reboot + Hourly)
# We check if the job already exists to avoid duplicates
(crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "@reboot $SCRIPT_PATH") | crontab -
(crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "0 * * * * $SCRIPT_PATH") | crontab -

echo "Done: Cron jobs added. Your DNS will now persist across reboots."