#!/bin/bash

# ============================================
# DNS Provider Options
# ============================================
# Luveedu DNS (Default) - Backed by Gcore
# Google DNS
# Cloudflare DNS
# Quad9 DNS
# OpenDNS
# ============================================

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default DNS (Luveedu)
DEFAULT_DNS1="95.85.95.85"
DEFAULT_DNS2="2.56.220.2"

SCRIPT_PATH="/usr/local/bin/dns-persist.sh"
RESOLV_CONF="/etc/resolv.conf"

# Check for root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: Please run with sudo.${NC}"
   exit 1
fi

# Function to detect system type
detect_system() {
    if command -v systemctl &>/dev/null && systemctl list-unit-files | grep -q systemd-resolved; then
        echo "systemd-resolved"
    elif command -v systemctl &>/dev/null && systemctl list-unit-files | grep -q NetworkManager; then
        echo "networkmanager"
    elif [[ -f /etc/network/interfaces ]] || [[ -d /etc/network/interfaces.d ]]; then
        echo "ifupdown"
    elif [[ -f /etc/netplan/*.yaml ]] 2>/dev/null; then
        echo "netplan"
    else
        echo "unknown"
    fi
}

# Function to display DNS menu
show_menu() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${GREEN}Select DNS Provider:${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo "1) Luveedu DNS (Default) - Backed by Gcore"
    echo "   Primary: 95.85.95.85 | Secondary: 2.56.220.2"
    echo ""
    echo "2) Google DNS"
    echo "   Primary: 8.8.8.8 | Secondary: 8.8.4.4"
    echo ""
    echo "3) Cloudflare DNS"
    echo "   Primary: 1.1.1.1 | Secondary: 1.0.0.1"
    echo ""
    echo "4) Quad9 DNS"
    echo "   Primary: 9.9.9.9 | Secondary: 149.112.112.112"
    echo ""
    echo "5) OpenDNS"
    echo "   Primary: 208.67.222.222 | Secondary: 208.67.220.220"
    echo ""
    echo "6) Custom DNS (Enter your own)"
    echo ""
    echo "0) Exit"
    echo -e "${BLUE}========================================${NC}"
}

# Function to set DNS based on selection
set_dns_by_selection() {
    case $1 in
        1)
            DNS1="95.85.95.85"
            DNS2="2.56.220.2"
            PROVIDER="Luveedu DNS (Gcore-backed)"
            ;;
        2)
            DNS1="8.8.8.8"
            DNS2="8.8.4.4"
            PROVIDER="Google DNS"
            ;;
        3)
            DNS1="1.1.1.1"
            DNS2="1.0.0.1"
            PROVIDER="Cloudflare DNS"
            ;;
        4)
            DNS1="9.9.9.9"
            DNS2="149.112.112.112"
            PROVIDER="Quad9 DNS"
            ;;
        5)
            DNS1="208.67.222.222"
            DNS2="208.67.220.220"
            PROVIDER="OpenDNS"
            ;;
        6)
            echo -e "${YELLOW}Enter primary DNS:${NC}"
            read -p "> " DNS1
            echo -e "${YELLOW}Enter secondary DNS:${NC}"
            read -p "> " DNS2
            PROVIDER="Custom DNS ($DNS1, $DNS2)"
            ;;
        0)
            echo -e "${YELLOW}Exiting...${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid option! Using default Luveedu DNS.${NC}"
            DNS1="$DEFAULT_DNS1"
            DNS2="$DEFAULT_DNS2"
            PROVIDER="Luveedu DNS (Default)"
            ;;
    esac
}

# Function to create persistence script
create_persistence_script() {
    cat <<EOF > $SCRIPT_PATH
#!/bin/bash
# DNS Persistence Script - Generated by nsetup.sh
# Provider: $PROVIDER
# DNS1: $DNS1
# DNS2: $DNS2

# Function to detect system type
detect_system() {
    if command -v systemctl &>/dev/null && systemctl list-unit-files | grep -q systemd-resolved; then
        echo "systemd-resolved"
    elif command -v systemctl &>/dev/null && systemctl list-unit-files | grep -q NetworkManager; then
        echo "networkmanager"
    elif [[ -f /etc/network/interfaces ]] || [[ -d /etc/network/interfaces.d ]]; then
        echo "ifupdown"
    elif [[ -f /etc/netplan/*.yaml ]] 2>/dev/null; then
        echo "netplan"
    else
        echo "unknown"
    fi
}

# Direct method for /etc/resolv.conf
echo "nameserver $DNS1" > $RESOLV_CONF
echo "nameserver $DNS2" >> $RESOLV_CONF

# System-specific methods
SYSTEM_TYPE=\$(detect_system 2>/dev/null || echo "unknown")

case \$SYSTEM_TYPE in
    systemd-resolved)
        # For systemd-resolved
        if command -v resolvectl &>/dev/null; then
            resolvectl dns \$DNS1 \$DNS2
            resolvectl domain
        fi
        ;;
    networkmanager)
        # For NetworkManager
        if command -v nmcli &>/dev/null; then
            # Get active connection
            CONN=\$(nmcli -t -f NAME,DEVICE,TYPE con show --active | grep ethernet | cut -d: -f1 | head -n1)
            if [[ -n "\$CONN" ]]; then
                nmcli con mod "\$CONN" ipv4.dns "\$DNS1 \$DNS2"
                nmcli con down "\$CONN" && nmcli con up "\$CONN"
            fi
        fi
        ;;
    netplan)
        # For Netplan
        if [[ -f /etc/netplan/*.yaml ]]; then
            # Update netplan config (simplified - user should verify)
            echo "Netplan detected. Please verify configuration in /etc/netplan/"
        fi
        ;;
esac
EOF

    chmod +x $SCRIPT_PATH
}

# Function to detect system and provide permanent solutions
permanent_solutions() {
    echo -e "\n${GREEN}========================================${NC}"
    echo -e "${BLUE}System Detection & Permanent Solutions:${NC}"
    echo -e "${GREEN}========================================${NC}"
    
    SYSTEM=$(detect_system)
    
    case $SYSTEM in
        systemd-resolved)
            echo -e "${GREEN}✓ Detected: systemd-resolved${NC}"
            echo -e "${YELLOW}For permanent solution, you can also:${NC}"
            echo "1. Edit /etc/systemd/resolved.conf:"
            echo "   [Resolve]"
            echo "   DNS=$DNS1 $DNS2"
            echo "   FallbackDNS=$DNS1 $DNS2"
            echo "   DNSSEC=yes"
            echo "2. Run: systemctl restart systemd-resolved"
            echo "3. Run: resolvectl status"
            ;;
        networkmanager)
            echo -e "${GREEN}✓ Detected: NetworkManager${NC}"
            echo -e "${YELLOW}For permanent solution:${NC}"
            echo "1. Edit /etc/NetworkManager/NetworkManager.conf:"
            echo "   [main]"
            echo "   dns=default"
            echo "2. Configure connection:"
            CONN=$(nmcli -t -f NAME,DEVICE,TYPE con show --active | grep ethernet | cut -d: -f1 | head -n1)
            if [[ -n "$CONN" ]]; then
                echo "   nmcli con mod \"$CONN\" ipv4.dns \"$DNS1 $DNS2\""
                echo "   nmcli con down \"$CONN\" && nmcli con up \"$CONN\""
            fi
            ;;
        ifupdown)
            echo -e "${GREEN}✓ Detected: ifupdown (Debian/Ubuntu legacy)${NC}"
            echo -e "${YELLOW}For permanent solution:${NC}"
            echo "1. Edit /etc/network/interfaces:"
            echo "   dns-nameservers $DNS1 $DNS2"
            echo "2. Or edit /etc/resolvconf/resolv.conf.d/head:"
            echo "   nameserver $DNS1"
            echo "   nameserver $DNS2"
            ;;
        netplan)
            echo -e "${GREEN}✓ Detected: Netplan${NC}"
            echo -e "${YELLOW}For permanent solution:${NC}"
            echo "1. Find your config: ls /etc/netplan/*.yaml"
            echo "2. Add/edit:"
            echo "   network:"
            echo "     ethernets:"
            echo "       eth0:"
            echo "         nameservers:"
            echo "           addresses: [$DNS1, $DNS2]"
            echo "3. Run: netplan apply"
            ;;
        *)
            echo -e "${YELLOW}⚠ Unknown system detected${NC}"
            echo "The cron-based persistence method will be used as fallback."
            ;;
    esac
    
    echo -e "\n${GREEN}Cron persistence is also configured (reboot + hourly).${NC}"
}

# Main script execution
clear
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}   DNS Persistence Installer v2.0${NC}"
echo -e "${BLUE}========================================${NC}"

# Show menu and get user choice
show_menu
echo -e "${YELLOW}Enter your choice [1-6, 0 to exit]:${NC}"
read -p "> " choice

# Validate choice
if [[ -z "$choice" ]]; then
    echo -e "${YELLOW}No input detected. Using default Luveedu DNS.${NC}"
    choice=1
fi

# Set DNS based on selection
set_dns_by_selection $choice

echo -e "\n${GREEN}Selected: $PROVIDER${NC}"
echo -e "Primary DNS: ${BLUE}$DNS1${NC}"
echo -e "Secondary DNS: ${BLUE}$DNS2${NC}"

# Confirm
echo -e "\n${YELLOW}Proceed with installation? (y/N)${NC}"
read -p "> " confirm

if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo -e "${RED}Installation cancelled.${NC}"
    exit 0
fi

# Create the persistence script
create_persistence_script

# Apply DNS immediately
$SCRIPT_PATH
echo -e "${GREEN}✓ DNS set to $PROVIDER ($DNS1, $DNS2)${NC}"

# Add to Cron for persistence
(crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "@reboot $SCRIPT_PATH") | crontab -
(crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "0 * * * * $SCRIPT_PATH") | crontab -
echo -e "${GREEN}✓ Cron jobs added (reboot + hourly)${NC}"

# Show system-specific permanent solutions
permanent_solutions

# Show status
echo -e "\n${GREEN}========================================${NC}"
echo -e "${BLUE}Current DNS Configuration:${NC}"
cat /etc/resolv.conf
echo -e "${GREEN}========================================${NC}"

# Additional instructions
echo -e "\n${BLUE}To check cron jobs:${NC}"
echo "  crontab -l | grep dns-persist"
echo -e "\n${BLUE}To change DNS later:${NC}"
echo "  sudo $0"
echo -e "\n${BLUE}To remove DNS persistence:${NC}"
echo "  crontab -l | grep -v dns-persist | crontab -"
echo "  rm $SCRIPT_PATH"
echo -e "\n${GREEN}Installation complete!${NC}"
